### ISSUE TITLE
Cannot install with dune-based build

### ISSUE THREAD

**Issue by goldfirere** [ocaml-flambda/ocaml-jst#54]
On a fresh checkout, if I

```
make -j -f Makefile.jst compiler
make install
```

then I get

```
mkdir -p "/home/reisenberg/local/ocaml/ocaml/rae_out/bin"
mkdir -p "/home/reisenberg/local/ocaml/ocaml/rae_out/lib/ocaml"
mkdir -p "/home/reisenberg/local/ocaml/ocaml/rae_out/lib/ocaml/stublibs"
mkdir -p "/home/reisenberg/local/ocaml/ocaml/rae_out/lib/ocaml/compiler-libs"
/bin/install -c -m 644 \
  VERSION \
  "/home/reisenberg/local/ocaml/ocaml/rae_out/lib/ocaml"
make -C runtime install
make[1]: Entering directory `/usr/local/home/reisenberg/ocaml/ocaml/runtime'
/bin/install -c ocamlrun ocamlrund ocamlruni "/home/reisenberg/local/ocaml/ocaml/rae_out/bin"
/bin/install: cannot stat ‘ocamlrun’: No such file or directory
/bin/install: cannot stat ‘ocamlrund’: No such file or directory
/bin/install: cannot stat ‘ocamlruni’: No such file or directory
make[1]: *** [install] Error 1
make[1]: Leaving directory `/usr/local/home/reisenberg/ocaml/ocaml/runtime'
make: *** [install] Error 2
```

(My install prefix is `$(pwd)/rae_out`.)

Have I made a mistake? Or is there a step missing in the new instructions? Thanks!

**Comment by goldfirere** [comment]
Also, I now have

```
> git status
On branch layout-annotations
Your branch is up to date with 'github/layout-annotations'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	dune-project
	duneconf/
	oc_cflags.sexp
	oc_cppflags.sexp
	ocamlopt_flags.sexp
	sharedlib_cflags.sexp
```

Is that expected? (Apologies if this should be a different ticket.)

**Comment by stedolan** [comment]
Ah, I missed a bit in the instructions. The dune-based build system is separate from the upstream Makefiles, so you need to do:
```
make -f Makefile.jst compiler
make -f Makefile.jst install
```
(The commands you had are the dune-based build, followed by trying to install result of the make-based build, and getting errors because the latter has not been built)

For the git-status, it looks like you switched to the main branch, ran the dune build (which creates various `.sexp`, etc. files which are `.gitignore`'d), then switched back to another branch (where these files are no longer ignored and show up in status). You can delete these files with `git clean` (or just delete them normally).
